/*
******************************************************************************
File:     main.c
Info:     Generated by Atollic TrueSTUDIO(R) 8.1.0   2017-12-22

The MIT License (MIT)
Copyright (c) 2009-2017 Atollic AB

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

******************************************************************************
*/

/* Includes */
#include <string.h>
#include "stm32f4xx.h"
#include "stm32f429i_discovery.h"
#include "stm32f429i_discovery_lcd.h"

/* Private macro */
/* Private variables */
/* Private function prototypes */
void LCD_DisplayWholeString(uint8_t StartLine, char *ptr);
/* Private functions */

/**
**===========================================================================
**
**  Abstract: initializes uart, receives data and shows it on LCD
**
**===========================================================================
*/
int main(void)
{

	/* LCD initiatization */
	LCD_Init();
	/* LCD Layer initiatization */
	LCD_LayerInit();
	/* Enable the LTDC */
	LTDC_Cmd(ENABLE);
	/* Set LCD foreground layer */
	LCD_SetLayer(LCD_FOREGROUND_LAYER);
	/* Clear the LCD */
	LCD_Clear(LCD_COLOR_BLACK);
	LCD_SetFont(&Font16x24);
	LCD_SetColors(LCD_COLOR_GREEN,LCD_COLOR_BLACK);

	/* Init GPIO Ports [PA9=TX, PA10=RX] for UART1 */
	GPIO_InitTypeDef GPIO_InitStruct;
	GPIO_StructInit(&GPIO_InitStruct);
	GPIO_InitStruct.GPIO_Speed = GPIO_Speed_2MHz;
	GPIO_InitStruct.GPIO_PuPd = GPIO_PuPd_UP;
	GPIO_InitStruct.GPIO_Mode = GPIO_Mode_AF;
	GPIO_InitStruct.GPIO_Pin = GPIO_Pin_9 | GPIO_Pin_10;
	GPIO_Init(GPIOA, &GPIO_InitStruct);

	// Set USART1 Peripherial Clock Ressource
	RCC_APB2PeriphClockCmd(RCC_APB2Periph_USART1, ENABLE);

	/* Init UART1 */
	USART_DeInit(USART1);
	// Init USART Clock
	USART_ClockInitTypeDef USART1_ClockInit;
	USART_ClockStructInit(&USART1_ClockInit);
	USART_ClockInit(USART1, &USART1_ClockInit);
	// Delete all content on the input buffer
	int deadloopprev;
	while ((USART_GetFlagStatus(USART1, USART_FLAG_RXNE ) == SET) &&
		 (deadloopprev < 10000))
	{
	  USART_ReceiveData(USART1);
	  deadloopprev++;
	}
	USART_Cmd(USART1, DISABLE);
	USART_InitTypeDef USART1_Init;
	USART_StructInit(&USART1_Init);
	USART_Init(USART1, &USART1_Init);
	USART_Cmd(USART1, ENABLE);

	// init USART Values
	char pc[144];
	for( int i = 0; i < 144; i++) pc[i]=0;
	uint8_t count = 143;

	/* Infinite loop */
	while (1)
	{
		int deadloopprev;
		while ((USART_GetFlagStatus(USART1, USART_FLAG_RXNE ) == RESET) &&
			 (deadloopprev < 10000))
		{
		  deadloopprev++;
		}
		deadloopprev = 0;
		while ((USART_GetFlagStatus(USART1, USART_FLAG_RXNE ) == SET) &&
			 (deadloopprev < 10000))
		{
		  for (int i = 0; i<=count; i++ )
		  {
			  uint16_t data_received;
			  data_received = USART_ReceiveData(USART1);
			  if (data_received <= 0xFF)
			  {
				  pc[i] = data_received;
			  }
		  }
		  deadloopprev++;
		}
		deadloopprev = 0;
		LCD_DisplayWholeString(0, pc);
	}
}

/*
 * Callback used by stm324xg_eval_i2c_ee.c.
 * Refer to stm324xg_eval_i2c_ee.h for more info.
 */
uint32_t sEE_TIMEOUT_UserCallback(void)
{
  /* TODO, implement your code here */
  while (1)
  {
  }
}

void LCD_DisplayWholeString(uint8_t StartLine, char *ptr)
{
	sFONT *CurrentFont;
	CurrentFont = LCD_GetFont();
	uint16_t LineLength = (LCD_PIXEL_WIDTH / CurrentFont->Width);
	int16_t StringLength = strlen(ptr);
	char *Segment = ptr;
	char LCDstring[LineLength];
	strncpy(LCDstring, ptr, LineLength);
	for (uint8_t CurrentLine = StartLine; StringLength > 0; CurrentLine+=CurrentFont->Height)
	{
		LCD_DisplayStringLine(CurrentLine, (uint8_t*) LCDstring);
		strncpy(LCDstring, Segment+=LineLength, LineLength);
		StringLength -= LineLength;
	}
}
